# Generated by Django 6.1.1 on 2026-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='İsim')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('school', models.CharField(max_length=200, verbose_name='Okul')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
